-- #################################################
-- Cleaning Step 1: Pruning clear ranges
-- FIRST: Get count of nulls:
--FinNULLS
-- SELECT 
-- 	SUM(CASE WHEN "m_housing_cg_fa" IS NULL THEN 1 ELSE 0 END) AS "null_1",
-- 	SUM(CASE WHEN "m12_housing_cg_fa" IS NULL THEN 1 ELSE 0 END) AS "null_2",
-- 	SUM(CASE WHEN "m_owned_housing_cg_fa" IS NULL THEN 1 ELSE 0 END) AS "null_3",
-- 	SUM(CASE WHEN "m12_owned_housing_cg_fa" IS NULL THEN 1 ELSE 0 END) AS "null_4",
-- 	SUM(CASE WHEN "m_investor_housing_cg_fa" IS NULL THEN 1 ELSE 0 END) AS "null_5",
-- 	SUM(CASE WHEN "m12_investor_housing_cg_fa" IS NULL THEN 1 ELSE 0 END) AS "null_6",
-- 	SUM(CASE WHEN "m_other_personal_cg_fa" IS NULL THEN 1 ELSE 0 END) AS "null_7",
-- 	SUM(CASE WHEN "m12_other_personal_cg_fa" IS NULL THEN 1 ELSE 0 END) AS "null_8",
-- 	SUM(CASE WHEN "m_non_financial_business_cg_fa" IS NULL THEN 1 ELSE 0 END) AS "null_9",
-- 	SUM(CASE WHEN "m12_non_financial_business_cg_fa" IS NULL THEN 1 ELSE 0 END) AS "null_10",
-- 	SUM(CASE WHEN "m_business_cg_fa" IS NULL THEN 1 ELSE 0 END) AS "null_11",
-- 	SUM(CASE WHEN "m12_business_cg_fa" IS NULL THEN 1 ELSE 0 END) AS "null_12",
-- 	SUM(CASE WHEN "m_select_fin_business_cg_fa" IS NULL THEN 1 ELSE 0 END) AS "null_13",
-- 	SUM(CASE WHEN "m12_select_fin_business_cg_fa" IS NULL THEN 1 ELSE 0 END) AS "null_14",
-- 	SUM(CASE WHEN "m_total_excfin_businss_cg_fa" IS NULL THEN 1 ELSE 0 END) AS "null_15",
-- 	SUM(CASE WHEN "m12_total_excfin_businss_cg_fa" IS NULL THEN 1 ELSE 0 END) AS "null_16",
-- 	SUM(CASE WHEN "m_total_cg_fa" IS NULL THEN 1 ELSE 0 END) AS "null_17",
-- 	SUM(CASE WHEN "m12_total_cg_fa" IS NULL THEN 1 ELSE 0 END) AS "null_18",
-- 	SUM(CASE WHEN "m_total_incselectfin_business_cg_fa" IS NULL THEN 1 ELSE 0 END) AS "null_19",
-- 	SUM(CASE WHEN "m12_total_incselectfin_business_cg_fa" IS NULL THEN 1 ELSE 0 END) AS "null_20",
-- 	SUM(CASE WHEN "m_m3_cg_fa" IS NULL THEN 1 ELSE 0 END) AS "null_21",
-- 	SUM(CASE WHEN "m12_m3_cg_fa" IS NULL THEN 1 ELSE 0 END) AS "null_22",
-- 	SUM(CASE WHEN "m_broad_money_cg_fa" IS NULL THEN 1 ELSE 0 END) AS "null_23",
-- 	SUM(CASE WHEN "m12_broad_money_cg_fa" IS NULL THEN 1 ELSE 0 END) AS "null_24"
-- FROM public.financial_aggregates_raw;
-- #################################################
--CreditNULLS
-- SELECT 
-- 	SUM(CASE WHEN "m_loans_advances_bank_excfin_lca" IS NULL THEN 1 ELSE 0 END) AS "null_1",
-- 	SUM(CASE WHEN "m_loans_advances_bank_lca" IS NULL THEN 1 ELSE 0 END) AS "null_2",
-- 	SUM(CASE WHEN "m_loans_advances_nbfi_excfin_lca" IS NULL THEN 1 ELSE 0 END) AS "null_3",
-- 	SUM(CASE WHEN "m_loans_advances_nbfi_lca" IS NULL THEN 1 ELSE 0 END) AS "null_4",
-- 	SUM(CASE WHEN "m_loans_advances_afi_excfin_lca" IS NULL THEN 1 ELSE 0 END) AS "null_5",
-- 	SUM(CASE WHEN "m_loans_advances_afi_lca" IS NULL THEN 1 ELSE 0 END) AS "null_6",
-- 	SUM(CASE WHEN "m_nonfin_issue_bills_lca" IS NULL THEN 1 ELSE 0 END) AS "null_7",
-- 	SUM(CASE WHEN "m_issue_bills_lca" IS NULL THEN 1 ELSE 0 END) AS "null_8",
-- 	SUM(CASE WHEN "m_narrow_c_excfin_lca" IS NULL THEN 1 ELSE 0 END) AS "null_9",
-- 	SUM(CASE WHEN "mseadj_narrow_c_excfin_lca" IS NULL THEN 1 ELSE 0 END) AS "null_10",
-- 	SUM(CASE WHEN "m_narrow_c_lca" IS NULL THEN 1 ELSE 0 END) AS "null_11",
-- 	SUM(CASE WHEN "mseadj_narrow_c_lca" IS NULL THEN 1 ELSE 0 END) AS "null_12",
-- 	SUM(CASE WHEN "m_total_c_excfin_lca" IS NULL THEN 1 ELSE 0 END) AS "null_13",
-- 	SUM(CASE WHEN "mseadj_total_c_excfin_lca" IS NULL THEN 1 ELSE 0 END) AS "null_14",
-- 	SUM(CASE WHEN "m_total_c_lca" IS NULL THEN 1 ELSE 0 END) AS "null_15",
-- 	SUM(CASE WHEN "m_total_c_lca" IS NULL THEN 1 ELSE 0 END) AS "null_16",
-- 	SUM(CASE WHEN "m_owner_housing_lca" IS NULL THEN 1 ELSE 0 END) AS "null_17",
-- 	SUM(CASE WHEN "mseadj_owner_housing_lca" IS NULL THEN 1 ELSE 0 END) AS "null_18",
-- 	SUM(CASE WHEN "m_investor_c_lca" IS NULL THEN 1 ELSE 0 END) AS "null_19",
-- 	SUM(CASE WHEN "mseadj_investor_c_lca" IS NULL THEN 1 ELSE 0 END) AS "null_20",
-- 	SUM(CASE WHEN "m_personal_c_lca" IS NULL THEN 1 ELSE 0 END) AS "null_21",
-- 	SUM(CASE WHEN "mseadj_personal_c_lca" IS NULL THEN 1 ELSE 0 END) AS "null_22",
-- 	SUM(CASE WHEN "m_nonfin_business_c_lca" IS NULL THEN 1 ELSE 0 END) AS "null_23",
-- 	SUM(CASE WHEN "mseadj_nonfin_business_lca" IS NULL THEN 1 ELSE 0 END) AS "null_24",
-- 	SUM(CASE WHEN "m_business_lca" IS NULL THEN 1 ELSE 0 END) AS "null_25",
-- 	SUM(CASE WHEN "mseadj_business_lca" IS NULL THEN 1 ELSE 0 END) AS "null_26",
-- 	SUM(CASE WHEN "m_govsector_lending_afi_lca" IS NULL THEN 1 ELSE 0 END) AS "null_27",
-- 	SUM(CASE WHEN "m_house_loan_switch_lca" IS NULL THEN 1 ELSE 0 END) AS "null_28",
-- 	SUM(CASE WHEN "m_total_incselectfin_business_lca" IS NULL THEN 1 ELSE 0 END) AS "null_29",
-- 	SUM(CASE WHEN "mseadj_total_incselectfin_business_lca" IS NULL THEN 1 ELSE 0 END) AS "null_30",
-- 	SUM(CASE WHEN "m_business_incselectfin_lca" IS NULL THEN 1 ELSE 0 END) AS "null_31",
-- 	SUM(CASE WHEN "mseadj_business_incselectfin_lca" IS NULL THEN 1 ELSE 0 END) AS "null_32"
-- FROM public.lending_credit_aggregates_raw;

-- #################################################

-- MonetaryNULLS
-- SELECT 
-- 	SUM(CASE WHEN "m_currency_ma" IS NULL THEN 1 ELSE 0 END) AS "null_1",
-- 	SUM(CASE WHEN "m_transaction_deposits_adi_ma" IS NULL THEN 1 ELSE 0 END) AS "null_2",
-- 	SUM(CASE WHEN "m_m1_ma" IS NULL THEN 1 ELSE 0 END) AS "null_3",
-- 	SUM(CASE WHEN "m_deposit_certificates_adi_ma" IS NULL THEN 1 ELSE 0 END) AS "null_4",
-- 	SUM(CASE WHEN "m_non_transaction_deposits_adi_ma" IS NULL THEN 1 ELSE 0 END) AS "null_5",
-- 	SUM(CASE WHEN "m_m3_ma" IS NULL THEN 1 ELSE 0 END) AS "null_6",
-- 	SUM(CASE WHEN "m_other_borrowing_privsect_afi_ma" IS NULL THEN 1 ELSE 0 END) AS "null_7",
-- 	SUM(CASE WHEN "m_broad_money_ma" IS NULL THEN 1 ELSE 0 END) AS "null_8",
-- 	SUM(CASE WHEN "mseadj_currency_ma" IS NULL THEN 1 ELSE 0 END) AS "null_9",
-- 	SUM(CASE WHEN "mseadj_m1_ma" IS NULL THEN 1 ELSE 0 END) AS "null_10",
-- 	SUM(CASE WHEN "mseadj_m3_ma" IS NULL THEN 1 ELSE 0 END) AS "null_11",
-- 	SUM(CASE WHEN "mseadj_broad_money_ma" IS NULL THEN 1 ELSE 0 END) AS "null_12",
-- 	SUM(CASE WHEN "m_base_money_ma" IS NULL THEN 1 ELSE 0 END) AS "null_13",
-- 	SUM(CASE WHEN "m_offshore_borrow_afi_ma" IS NULL THEN 1 ELSE 0 END) AS "null_14"
-- FROM public.monetary_aggregates_raw;
